# Generated by Django 4.2.2 on 2023-07-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='language',
        ),
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(to='movie.movie'),
        ),
    ]
